document.getElementById('send-button').addEventListener('click', sendMessage);

document.getElementById('user-input').addEventListener('keypress', function(e) {
    if (e.key === 'Enter') {
        sendMessage();
    }
});

function sendMessage() {
    const userInput = document.getElementById('user-input').value;
    if (userInput.trim() === '') return;

    addMessage(userInput, 'user-message');

    // Simulate a bot response (replace this with an actual API call in a real app)
    setTimeout(() => {
        addMessage('This is a static response from GrantGPT. In a real application, this would be generated by an AI model.', 'bot-message');
    }, 500);

    document.getElementById('user-input').value = '';
}

function addMessage(message, className) {
    const messageElement = document.createElement('div');
    messageElement.classList.add('chat-message', className);
    messageElement.textContent = message;
    document.getElementById('chat-box').appendChild(messageElement);
    messageElement.scrollIntoView({ behavior: 'smooth' });
}
